apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntfy-pushover-forwarder.fullname" . }}
  labels:
    {{- include "ntfy-pushover-forwarder.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Forwarder": {
        "NtfyUrl": "{{ .Values.forwarder.ntfyUrl }}",
        "MinimumPriority": {{ .Values.forwarder.minimumPriority | default 1 }},
        "Topics": {{ toJson .Values.forwarder.topics }},
        "SoundMap": {{ toJson .Values.forwarder.soundMap }},
        "LogoMap": {{ toJson .Values.forwarder.logoMap }}
      }
    }
