apiVersion: v2
name: ntfy-pushover-forwarder
description: A .NET 9 worker service that forwards ntfy messages to Pushover with custom sound and logo mappings.
type: application
version: 0.1.2
appVersion: "latest"
